language: ruby
script:
  - npm install webpack -g
  - npm install webpack-cli -g
  - npm install
  - NODE_ENV=production webpack --mode=production
  - bundle exec jekyll build
deploy:
  provider: surge
  project: _site
  domain: beta.metlika.eu
  skip_cleanup: true